# Directory args
input: data/sample_inputs/streamed_frames/left
input_right: data/sample_inputs/streamed_frames/right
input_metadata: data/sample_inputs/streamed_frames/metadata
output: output/output_streamed

external_geometry_path:   # path to yaml, required when geometry_source == external

# Boolean/enum args
depth_source: stereo # mono | stereo
geometry_source: metadata # metadata | external | estimation 
pose_source: metadata # metadata | estimation
visualize: true

# 2D scene graph generator [deprecated]
sgg2d_config:
ssg2d_ckpt:

# Depth estimator
depth_config: configs/ffstereo.yaml
depth_ckpt: checkpoints/ffstereo.pth

# Pose estimator
pose_config: configs/dvpo.yaml
pose_ckpt: checkpoints/dpvo.pth

# Tracker
tracker_config: configs/trackon2.yaml
tracker_ckpt: checkpoints/trackon2_dinov3_checkpoint.pt

# Detector
detector_config:
detector_ckpt:

# Point lifter
point_lifter_config:

# 3D scene graph generator
3dsgg_config:

# 3D scene graph merger
3dsg_merging_config:
